// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACOmo4chQNNoKn9VyqMULX1d07DzcJghQ',
    appId: '1:140234204311:web:1d32762a7c4536babdb5d2',
    messagingSenderId: '140234204311',
    projectId: 'fir-auth-ad8a6',
    authDomain: 'fir-auth-ad8a6.firebaseapp.com',
    storageBucket: 'fir-auth-ad8a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD17eStdTvy-lND7aFMY8ijmRt6lIm74fI',
    appId: '1:140234204311:android:556e990286b844bebdb5d2',
    messagingSenderId: '140234204311',
    projectId: 'fir-auth-ad8a6',
    storageBucket: 'fir-auth-ad8a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSgjmnBcrSDKlAVtmSR_Ztd6HZhL2f8No',
    appId: '1:140234204311:ios:8b19d377f5bbf1b0bdb5d2',
    messagingSenderId: '140234204311',
    projectId: 'fir-auth-ad8a6',
    storageBucket: 'fir-auth-ad8a6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSgjmnBcrSDKlAVtmSR_Ztd6HZhL2f8No',
    appId: '1:140234204311:ios:8b19d377f5bbf1b0bdb5d2',
    messagingSenderId: '140234204311',
    projectId: 'fir-auth-ad8a6',
    storageBucket: 'fir-auth-ad8a6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACOmo4chQNNoKn9VyqMULX1d07DzcJghQ',
    appId: '1:140234204311:web:fb23aa4acaaad6cabdb5d2',
    messagingSenderId: '140234204311',
    projectId: 'fir-auth-ad8a6',
    authDomain: 'fir-auth-ad8a6.firebaseapp.com',
    storageBucket: 'fir-auth-ad8a6.firebasestorage.app',
  );
}
